// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbothzkxjclgjoxiftuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpib3Roemt4amNsZ2pveGlmdHV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0ODY2MDIsImV4cCI6MjA2MDA2MjYwMn0.JjcveFYpUO95luA3TtqIUnJtAvMEiusVA-zixT3GTPo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);